apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth
  namespace: openshift-gitops
spec:
  project: formation-openshift
  source:
    repoURL: https://github.com/neutron-IT-organization/formation-openshift-gitops.git
    targetRevision: main
    path: gitops/auth/chart
    helm:
      parameters:
      - name: masterKey
        value: my-secret-value
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
    - CreateNamespace=false
    automated:
      selfHeal: true
      prune: true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
