apiVersion: apps/v1
kind: Deployment
metadata:
  name: probes-app
  labels:
    app: probes-app
    formation: l06p01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: probes-app
  template:
    metadata:
      labels:
        app: probes-app
    spec:
      containers:
        - name: probes-app
          image: quay.io/neutron-it/probes-app:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
