apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: solution-configmap-secrets
  namespace: openshift-gitops
spec:
  generators:
  - list:
      elements:
      - city: tokyo
      - city: paris
      - city: londres
      - city: rome
      - city: sydney
      - city: rio
      - city: istanbul
      - city: berlin
      - city: nairobi
      - city: madrid
  template:
    metadata:
      name: 'solution-configmap-secrets-{{city}}'
    spec:
      project: formation-openshift
      source:
        repoURL: https://github.com/neutron-IT-organization/formation-openshift-gitops.git
        targetRevision: main
        path: gitops/solution-configmap-secrets/base
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{city}}-user-ns'
      syncPolicy:
        syncOptions:
          - CreateNamespace=false
