apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcome-app
  labels:
    app: welcome-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: welcome-app
  template:
    metadata:
      labels:
        app: welcome-app
    spec:
      containers:
        - name: welcome-app-container
          image: quay.io/neutron-it/welcome-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: welcome-app-config
            - secretRef:
                name: welcome-app-secret
          resources:
            requests:
              cpu: "1m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
