apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: l02p01
  namespace: openshift-gitops
spec:
  project: formation-openshift
  source:
    repoURL: https://github.com/neutron-IT-organization/formation-openshift-gitops.git
    targetRevision: main
    path: gitops/l02p01/base
  destination:
    server: https://kubernetes.default.svc
    namespace: l02p01
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
