apiVersion: apps/v1
kind: Deployment
metadata:
  name: probes-app
  labels:
    app: probes-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: probes-app
  template:
    metadata:
      labels:
        app: probes-app
    spec:
      containers:
        - name: probes-app
          image: quay.io/neutron-it/probes-app:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: "1m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
