apiVersion: apps/v1
kind: Deployment
metadata:
  name: shared-app
  labels:
    app: shared-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shared-app
  template:
    metadata:
      labels:
        app: shared-app
    spec:
      containers:
        - name: web-container
          image: registry.access.redhat.com/ubi8/ubi:latest
          command: ["/bin/bash"]
          args:
            ["-c", "echo hello from neutron IT; while true; do sleep 10; done"]
