apiVersion: apps/v1
kind: Deployment
metadata:
  name: p02l03-app
  labels:
    app: p02l03-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: p02l03-quarkus-aap
  template:
    metadata:
      labels:
        app: p02l03-quarkus-aap
    spec:
      containers:
        - name: quarkus-container
          image: registry.access.redhat.com/ubi8/ubi:latest
          command: ["/bin/bash"]
          args:
            ["-c", "echo hello from neutron IT; while true; do sleep 10; done"]

