apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: formation-openshift
  namespace: openshift-gitops
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - name: '*'
    namespace: '*'
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - https://github.com/neutron-IT-organization/formation-openshift-gitops.git
