openshift:
  # Mot de passe commun pour tous les utilisateurs de la formation
  # IMPORTANT: Changez ce mot de passe avant la formation !
  defaultPassword: "OpenShift4formation!"

  users:
  - tokyo
  - paris
  - londres
  - rome
  - sydney
  - rio
  - istanbul
  - berlin
  - nairobi
  - madrid
  - toronto
  - singapour
  - stockholm
  - athenes
  - varsovie
  - oslo
  - helsinki
  - lisbonne
  - vienne
  - brasilia
  - canberra
  - ottawa
  - seoul
  - cap
  - budapest
  - dublin
  - zurich
  - cardiff
  - nicosie
  - sofia
  - suva
  - riga
  - vilnius
  - alger
  - abou-dabi
  - bagdad
  - bangkok
  - le-caire
  - freetown
  - kaboul
  - kinshasa
  - libreville
  - mexico
  - reykjavik
  - prague

  # Quotas appliqués à chaque namespace étudiant
  namespace:
    quota:
      requestsCpu: "0.2"
      requestsMemory: "512Mi"
      limitsCpu: "0.5"
      limitsMemory: "1Gi"
      pods: "10"
      services: "10"
      persistentvolumeclaims: "5"
      requestsStorage: "20Gi"
    limitrange:
      defaultCpu: "50m"
      defaultMemory: "64Mi"
      defaultRequestCpu: "1m"
      defaultRequestMemory: "16Mi"
      maxCpu: "2"
      maxMemory: "2Gi"
